name: Format Check

on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

jobs:
    spotless:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 22

            - name: Run Spotless check
              run: ./mvnw spotless:check
